#!/bin/sh

# ================== VARIABLES ==================

# OS info
. /etc/os-release
osName="$NAME"
osVersion="$VERSION"
os="$osName $osVersion"

# Uptime
uptimeInfo=$(uptime -p)

# CPU info
cpuVendor=$(grep "vendor_id" /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^ //')
cpuModel=$(grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^ //')
cpu="$cpuVendor $cpuModel"

# RAM info
ram=$(free -h | awk '/Mem:/ {print $2}')

# Disk info
disks=$(lsblk -d -o NAME,MODEL,SIZE | awk 'NR>1 {if($2!="") print $2" "$3; else print $1" "$3}')
realDisks=$(echo "$disks" | grep -v -i 'vmware\|virtualbox')
virtualDisks=$(echo "$disks" | grep -i 'vmware\|virtualbox')
diskLine=$(echo $realDisks | tr '\n' '\t')
virtualLine=$(echo $virtualDisks | tr '\n' '\t')

# Video info
video=$(lspci | grep -i 'vga\|3d' | sed 's/^[^:]*: //' | tr '\n' ',' | sed 's/,$//')

# Network info
gatewayIp=$(ip route | awk '/default/ {print $3}')
gatewayInterface=$(ip route | awk '/default/ {print $5}')
hostIp=$(ip -4 addr show $gatewayInterface | awk '/inet / {print $2}' | cut -d/ -f1)
dnsServers=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd "," -)

# Host and user info
hostName=$(hostname)
userName=$(whoami)
dateTime=$(date +"%Y-%m-%d %H:%M:%S")
kernelVersion=$(uname -r)

# System Status info
usersLoggedIn=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)
diskSpace=$(df -h --local | awk 'NR>1 {print $6 " " $4}' | paste -sd ", " -)
processCount=$(ps -e --no-headers | wc -l)
loadAverages=$(uptime | awk -F'load average:' '{print $2}' | sed 's/^ //')
listeningPorts=$(ss -tuln | awk 'NR>1 {print $5}' | cut -d':' -f2 | sort -n | uniq | paste -sd "," -)
if command -v ufw >/dev/null 2>&1; then
    ufwStatus=$(sudo ufw status | head -1)
else
    ufwStatus="ufw not installed"
fi

# ================== ECHO OUTPUT ==================

echo "System Report for $hostName generated by $userName, on $dateTime"
echo
echo "System Information"
echo "------------------"
echo "OS: $os"
echo "Uptime: $uptimeInfo"
echo "CPU: $cpu"
echo "RAM: $ram"
echo -e "Disk(s):\t$diskLine"
[ -n "$virtualLine" ] && echo -e "Virtual:\t$virtualLine"
echo "Video: $video"
echo "Host Address: $hostIp"
echo "Gateway IP: $gatewayIp"
echo "DNS Server: $dnsServers"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $usersLoggedIn"
echo "Disk Space: $diskSpace"
echo "Process Count: $processCount"
echo "Load Averages: $loadAverages"
echo "Listening Network Ports: $listeningPorts"
echo "UFW Status: $ufwStatus"
